### ISSUE TITLE
learning wondering

### ISSUE THREAD

**Issue by kyrosle** [ElliotB256/bevy_combat#5]
Hello bro, i feel confused in the package combat. In the Plugin system: add_effect and remove_old_effect, in my thought, these two system may work in the same update every times, the weapon entity effect may be created with component and this will be despawned
in the same update, but in the game it seems that can last until the animation finished. Looking forwoard to you reply bro.

**Comment by ElliotB256** [comment]
Hey @kyrosle, the effects in combat refer to single frame effects like taking damage, healing, etc. The creation and destruction systems run in the same stage, which actually means the entities should live for a single frame - structural changes are delayed until the end of the current stage, so first the effect is spawned, but then it needs to wait until the next frame to despawn them.

These are different from the animation effects like explosions and beams, which are spawned as 'fire and forget' and live as their own entities for a few frames. They can largely be found here: https://github.com/ElliotB256/bevy_combat/blob/master/src/fx/animated.rs

Hope this helps!

**Comment by kyrosle** [comment]
Oh I understand the design , i feel so amazing, thanks bro
